export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const RESET_USER = 'RESET_USER';

//Logout
export const LOGOUT_USER = 'LOGOUT_USER';

// PARTY
export const CREATE_PARTY_SUCCESS = 'CREATE_PARTY_SUCCESS';
export const CREATE_PARTY_FAILURE = 'CREATE_PARTY_FAILURE';
export const FETCH_PARTIES = 'FETCH_PARTIES';
export const FETCH_SINGLE_PARTY = 'FETCH_SINGLE_PARTY';
